// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class IdolDefense
{
        public const string event_miki_sold = "CgkIjMvusJ4eEAIQGA"; // <GPGSID>
        public const string event_haruka_sold = "CgkIjMvusJ4eEAIQEA"; // <GPGSID>
        public const string achievement_chihaya_unique = "CgkIjMvusJ4eEAIQNA"; // <GPGSID>
        public const string event_iori_summoned = "CgkIjMvusJ4eEAIQDQ"; // <GPGSID>
        public const string event_clear_20 = "CgkIjMvusJ4eEAIQHQ"; // <GPGSID>
        public const string event_clear_30 = "CgkIjMvusJ4eEAIQHg"; // <GPGSID>
        public const string event_clear_10 = "CgkIjMvusJ4eEAIQHA"; // <GPGSID>
        public const string event_clear_60 = "CgkIjMvusJ4eEAIQIQ"; // <GPGSID>
        public const string event_clear_70 = "CgkIjMvusJ4eEAIQIg"; // <GPGSID>
        public const string event_clear_40 = "CgkIjMvusJ4eEAIQHw"; // <GPGSID>
        public const string event_clear_50 = "CgkIjMvusJ4eEAIQIA"; // <GPGSID>
        public const string event_yukiho_sold = "CgkIjMvusJ4eEAIQDw"; // <GPGSID>
        public const string achievement_producer_run = "CgkIjMvusJ4eEAIQPQ"; // <GPGSID>
        public const string leaderboard_iori_kills = "CgkIjMvusJ4eEAIQSA"; // <GPGSID>
        public const string achievement_chihaya_mster = "CgkIjMvusJ4eEAIQJQ"; // <GPGSID>
        public const string achievement_iori_mster = "CgkIjMvusJ4eEAIQKw"; // <GPGSID>
        public const string leaderboard_mami_kills = "CgkIjMvusJ4eEAIQQQ"; // <GPGSID>
        public const string achievement_hibiki_unique = "CgkIjMvusJ4eEAIQMA"; // <GPGSID>
        public const string event_azusa_sold = "CgkIjMvusJ4eEAIQGw"; // <GPGSID>
        public const string event_iori_sold = "CgkIjMvusJ4eEAIQGg"; // <GPGSID>
        public const string event_azusa_summoned = "CgkIjMvusJ4eEAIQDg"; // <GPGSID>
        public const string achievement_b_rank_producer = "CgkIjMvusJ4eEAIQOA"; // <GPGSID>
        public const string event_makoto_sold = "CgkIjMvusJ4eEAIQFw"; // <GPGSID>
        public const string event_chihaya_sold = "CgkIjMvusJ4eEAIQEw"; // <GPGSID>
        public const string event_hibiki_summoned = "CgkIjMvusJ4eEAIQCw"; // <GPGSID>
        public const string achievement_c_rank_producer = "CgkIjMvusJ4eEAIQPg"; // <GPGSID>
        public const string event_mami_sold = "CgkIjMvusJ4eEAIQEg"; // <GPGSID>
        public const string leaderboard_azusa_kills = "CgkIjMvusJ4eEAIQSQ"; // <GPGSID>
        public const string achievement_mami_mster = "CgkIjMvusJ4eEAIQJA"; // <GPGSID>
        public const string event_yukiho_summoned = "CgkIjMvusJ4eEAIQBA"; // <GPGSID>
        public const string achievement_yayoi_mster = "CgkIjMvusJ4eEAIQJg"; // <GPGSID>
        public const string achievement_ami_mster = "CgkIjMvusJ4eEAIQIw"; // <GPGSID>
        public const string achievement_azusa_mster = "CgkIjMvusJ4eEAIQLA"; // <GPGSID>
        public const string achievement_yayoi_no_yume = "CgkIjMvusJ4eEAIQPA"; // <GPGSID>
        public const string achievement_haruka_unique = "CgkIjMvusJ4eEAIQNg"; // <GPGSID>
        public const string achievement_hruk_mster = "CgkIjMvusJ4eEAIQAw"; // <GPGSID>
        public const string achievement_miki_unique = "CgkIjMvusJ4eEAIQLw"; // <GPGSID>
        public const string event_haruka_summoned = "CgkIjMvusJ4eEAIQBQ"; // <GPGSID>
        public const string event_miki_summoned = "CgkIjMvusJ4eEAIQDA"; // <GPGSID>
        public const string leaderboard_makoto_kills = "CgkIjMvusJ4eEAIQRA"; // <GPGSID>
        public const string event_takane_sold = "CgkIjMvusJ4eEAIQFQ"; // <GPGSID>
        public const string event_yayoi_summoned = "CgkIjMvusJ4eEAIQCA"; // <GPGSID>
        public const string achievement_takane_unique = "CgkIjMvusJ4eEAIQMQ"; // <GPGSID>
        public const string event_makoto_summoned = "CgkIjMvusJ4eEAIQCQ"; // <GPGSID>
        public const string event_yayoi_sold = "CgkIjMvusJ4eEAIQFA"; // <GPGSID>
        public const string leaderboard_ami_kills = "CgkIjMvusJ4eEAIQQA"; // <GPGSID>
        public const string leaderboard_haruka_kills = "CgkIjMvusJ4eEAIQPw"; // <GPGSID>
        public const string event_mami_summoned = "CgkIjMvusJ4eEAIQGQ"; // <GPGSID>
        public const string achievement_s_rank_producer = "CgkIjMvusJ4eEAIQOg"; // <GPGSID>
        public const string achievement_yayoi_unique = "CgkIjMvusJ4eEAIQMg"; // <GPGSID>
        public const string event_hibiki_sold = "CgkIjMvusJ4eEAIQFg"; // <GPGSID>
        public const string event_takane_summoned = "CgkIjMvusJ4eEAIQCg"; // <GPGSID>
        public const string achievement_takane_mster = "CgkIjMvusJ4eEAIQJw"; // <GPGSID>
        public const string leaderboard_takane_kills = "CgkIjMvusJ4eEAIQRQ"; // <GPGSID>
        public const string achievement_makoto_unique = "CgkIjMvusJ4eEAIQMw"; // <GPGSID>
        public const string achievement_a_rank_producer = "CgkIjMvusJ4eEAIQOQ"; // <GPGSID>
        public const string event_futami_summoned = "CgkIjMvusJ4eEAIQBg"; // <GPGSID>
        public const string achievement_miki_mster = "CgkIjMvusJ4eEAIQKg"; // <GPGSID>
        public const string leaderboard_yukiho_kills = "CgkIjMvusJ4eEAIQAQ"; // <GPGSID>
        public const string achievement_iori_beam = "CgkIjMvusJ4eEAIQLg"; // <GPGSID>
        public const string achievement_futami_unique = "CgkIjMvusJ4eEAIQNQ"; // <GPGSID>
        public const string achievement_yukiho_mster = "CgkIjMvusJ4eEAIQAg"; // <GPGSID>
        public const string leaderboard_hibiki_kills = "CgkIjMvusJ4eEAIQRg"; // <GPGSID>
        public const string achievement_makoto_mster = "CgkIjMvusJ4eEAIQKQ"; // <GPGSID>
        public const string achievement_hibiki_mster = "CgkIjMvusJ4eEAIQKA"; // <GPGSID>
        public const string achievement_azusa_storm = "CgkIjMvusJ4eEAIQLQ"; // <GPGSID>
        public const string event_ami_sold = "CgkIjMvusJ4eEAIQEQ"; // <GPGSID>
        public const string achievement_yukiho_unique = "CgkIjMvusJ4eEAIQNw"; // <GPGSID>
        public const string event_chihaya_summoned = "CgkIjMvusJ4eEAIQBw"; // <GPGSID>
        public const string leaderboard_miki_kills = "CgkIjMvusJ4eEAIQRw"; // <GPGSID>
        public const string leaderboard_yayoi_kills = "CgkIjMvusJ4eEAIQQw"; // <GPGSID>
        public const string achievement_shiika_no_tameni = "CgkIjMvusJ4eEAIQOw"; // <GPGSID>
        public const string leaderboard_chihaya_kills = "CgkIjMvusJ4eEAIQQg"; // <GPGSID>

}

